#################################################
#  SLAM/GPS Pose graph optimization parameters  #
#################################################

n_iterations: 1000
time_offset: 0.  # GPS time = SLAM time + TimeOffset
tf_gps_to_sensor: [0.121, -0.197, 0.173, 0., 0.3, 0.]  # (x, y, z, rx, ry, rz) Pose of the sensor that produces the trajectory to optimize in GPS antenna cordinates.
# tf_gps_to_sensor: [0., 0., 0., 0., 0., 0.]  # (x, y, z, rx, ry, rz) Pose of the sensor that produces the trajectory to optimize in GPS antenna cordinates.
verbose: true
g2o_file_name: "/home/nicolas/pose_graph_optimization.g2o"