#####################################
#  Real-time LiDAR SLAM parameters  #
#####################################

## number of vertical lasers in LiDAR sensor (optional : if not given, it will be guessed from 1st frame)
# n_lasers: 16

## mapping from ring id to laser id (optional, default : identity mapping)
# laser_id_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

# frame_id of SLAM map origin. SLAM will publish the TF slam_origin_frame -> velodyne.
slam_origin_frame: "slam_init"

# optional publishers
publish_features_maps:
  edges: true     # if true, edges features will be published to topic "edges_features"
  planars: true   # if true, planars features will be published to topic "planars_features"
  blobs: true     # if true, blobs features will be published to topic "blobs_features"
