FROM osrf/ros:humble-desktop-full
LABEL maintainer="Julia Sanchez julia.sanchez@kitware.com"

WORKDIR /tmp

RUN apt update

# Install Slam ROS dependencies
RUN apt install -y ros-$ROS_DISTRO-velodyne

# Install Slam dependencies
COPY deps_install_scripts/install_deps.sh install_deps.sh
RUN sh install_deps.sh

COPY deps_install_scripts/install_ceres.sh install_ceres.sh
RUN sh install_ceres.sh

COPY deps_install_scripts/install_nanoflann.sh install_nanoflann.sh
RUN sh install_nanoflann.sh

COPY deps_install_scripts/install_g2o.sh install_g2o.sh
RUN sh install_g2o.sh

# Graphic display on host
RUN apt -y install libgl1-mesa-glx libgl1-mesa-dri

# Erase apt cache
RUN rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/ros_entrypoint.sh"]

WORKDIR /root