# Default variables/parameters for all jobs
variables:
  data_folder: /usr/src/app/data
  cmake_option_GENERATOR: -GNinja
  cmake_option_build_type: -DCMAKE_BUILD_TYPE=Release
  cmake_option_shared: -DBUILD_SHARED_LIBS=ON
  SB_deps_install_path: "${CI_PROJECT_DIR}/../${CI_PROJECT_NAME}_build/build_SB/install"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 20

stages:
  - superbuild
  - slam_lib
  - ros_wrapping_build
  - ros_test
  - paraview_wrapping

# Windows specific configuration
.windows_runner_config:
  before_script:
    # To use the Microsoft C++ Toolset from the command line, some environment variables need to be set.
    # To help with this, Microsoft provides the vcvarsall.bat script that sets different environment vars.
    # (see https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019)
    # However, the script is made for the command shell and the job run in a powershell.
    # A powershell can run a command shell script by using the `cmd` executable, but this implies
    # that environment variables are only set in the child cmd.exe instance. The environment variables need to
    # be updated in the powershell too. This is why the function Invoke-CmdScript is needed as it invokes
    # the script and updates the powershell environment.
    # This is taken from https://stackoverflow.com/a/41399983
    - | # pipe allows to use multiline command, see https://gitlab.com/gitlab-org/gitlab-runner/issues/166
      function Invoke-CmdScript {
        param(
          [String] $scriptName
        )
        $cmdLine = """$scriptName"" $args & set"
        & $Env:SystemRoot\system32\cmd.exe /c $cmdLine |
          Select-String '^([^=]*)=(.*)$' |
          ForEach-Object {
            $varName = $_.Matches[0].Groups[1].Value
            $varValue = $_.Matches[0].Groups[2].Value
            Set-Item Env:$varName $varValue
        }
      }
    - Invoke-CmdScript "${vcvarsall_script_location}/vcvarsall.bat" $architecture
  variables:
    # Paraview only supports MSVC 2019 and Ninja generator for now
    vcvarsall_script_location: 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build'
    architecture: x86_amd64

# ------------------------------------------------------------------------------
#   Build superbuild
# ------------------------------------------------------------------------------

# Clean superbuild
clean_superbuild:
  stage: superbuild
  tags: [superbuild]
  needs: []
  variables:
    build_dir: "${CI_PROJECT_DIR}/../${CI_PROJECT_NAME}_build/build_SB"
  rules:
    # Can be launched only from the web interface
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  script:
    - cmake -E remove_directory $build_dir

# Build superbuild
.build_superbuild:
  stage: superbuild
  tags: [superbuild]
  variables:
    build_dir: "${CI_PROJECT_DIR}/../${CI_PROJECT_NAME}_build/build_SB"
  rules:
    # Can be launched only from the web interface
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  script:
    - cmake -E make_directory $build_dir
    - cd $build_dir
    - echo "cmake ${CI_PROJECT_DIR}/slam-superbuild
      $cmake_option_GENERATOR
      $cmake_option_build_type
      -DCMAKE_INSTALL_PREFIX=$SB_deps_install_path
      -DBUILD_SLAM_SHARED_LIBS=OFF"
    - cmake "${CI_PROJECT_DIR}/slam-superbuild"
      $cmake_option_GENERATOR
      $cmake_option_build_type
      -DCMAKE_INSTALL_PREFIX="$SB_deps_install_path"
      -DBUILD_SLAM_SHARED_LIBS=OFF
    - cmake --build . -j 4

# Build superbuild on Windows
# This job allows to store the dependencies
# for next CI run on windows runners
windows_build_superbuild:
  tags: [windows]
  extends:
  - .windows_runner_config
  - .build_superbuild

# Build superbuild on Linux
# This job allows to store the dependencies
# for next CI run on linux runners
linux_build_superbuild:
  tags: [linux]
  extends:
    - .build_superbuild

# ------------------------------------------------------------------------------
#   Build core LidarSlam lib
# ------------------------------------------------------------------------------

.slam_lib:
  stage: slam_lib
  needs: []
  tags: [superbuild]
  variables:
    build_dir: "${CI_PROJECT_DIR}/../${CI_PROJECT_NAME}_build/build_slam_lib"
    slam_cmake_option_Eigen_INCLUDE_DIR: "-DEigen_INCLUDE_DIR=${SB_deps_install_path}/include"
    slam_cmake_option_Eigen_DIR: "-DEigen3_DIR=${SB_deps_install_path}/share/eigen3/cmake"
    slam_cmake_option_glog_DIR: "-Dglog_DIR=${SB_deps_install_path}/lib/cmake/glog"
    slam_cmake_option_Ceres_DIR: "-DCeres_DIR=${SB_deps_install_path}/lib/cmake/Ceres"
    slam_cmake_option_nanoflann_DIR: "-Dnanoflann_DIR=${SB_deps_install_path}/share/nanoflann/cmake"
    slam_cmake_option_BOOST_ROOT: "-DBOOST_ROOT=${SB_deps_install_path}/"
    slam_cmake_option_Boost_STATIC: "-DBoost_USE_STATIC_LIBS=OFF"
    slam_cmake_option_g2o_DIR: "-Dg2o_DIR=${SB_deps_install_path}/lib/cmake/g2o"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
  script:
    - cmake -E remove_directory $build_dir
    - cmake -E make_directory $build_dir
    - cd $build_dir
    - echo "cmake $CI_PROJECT_DIR
      $cmake_option_GENERATOR
      $cmake_option_build_type
      $cmake_option_shared
      $slam_cmake_option_Eigen_INCLUDE_DIR
      $slam_cmake_option_Eigen_DIR
      $slam_cmake_option_glog_DIR
      $slam_cmake_option_Ceres_DIR
      $slam_cmake_option_nanoflann_DIR
      $slam_cmake_option_BOOST_ROOT
      $slam_cmake_option_Boost_STATIC
      $slam_cmake_option_PCL_DIR
      $slam_cmake_option_g2o_DIR"
    - cmake $CI_PROJECT_DIR
      $cmake_option_GENERATOR
      $cmake_option_build_type
      $cmake_option_shared
      $slam_cmake_option_Eigen_INCLUDE_DIR
      $slam_cmake_option_Eigen_DIR
      $slam_cmake_option_glog_DIR
      $slam_cmake_option_Ceres_DIR
      $slam_cmake_option_nanoflann_DIR
      $slam_cmake_option_BOOST_ROOT
      $slam_cmake_option_Boost_STATIC
      $slam_cmake_option_PCL_DIR
      $slam_cmake_option_g2o_DIR
    - cmake --build $build_dir -j 4

# Build core LidarSlam lib on Linux
linux_slam_lib:
  tags: [linux, superbuild]
  extends:
    - .slam_lib
  variables:
    slam_cmake_option_PCL_DIR: "-DPCL_DIR=${SB_deps_install_path}/share/pcl-1.13"

# Build core LidarSlam lib on Windows
windows_slam_lib:
  tags: [windows]
  extends:
  - .windows_runner_config
  - .slam_lib
  variables:
    slam_cmake_option_PCL_DIR: "-DPCL_DIR=${SB_deps_install_path}/cmake"

# ------------------------------------------------------------------------------
#   Build PV wrapping
# ------------------------------------------------------------------------------

# Note : Paraview, qt, zlib, png and python deps
# should be configured in runners' toml files.
.paraview_wrapping:
  stage: paraview_wrapping
  needs: []
  variables:
    build_dir: "${CI_PROJECT_DIR}/../${CI_PROJECT_NAME}_build/build_paraview_wrapping"
    slam_cmake_option_Boost_STATIC: "-DBoost_USE_STATIC_LIBS=OFF"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
  script:
    - cmake -E remove_directory $build_dir
    - cmake -E make_directory $build_dir
    - cd $build_dir
    - echo "cmake $CI_PROJECT_DIR
      $cmake_option_GENERATOR
      $cmake_option_build_type
      $cmake_option_shared
      -DSLAM_PARAVIEW_PLUGIN=ON
      $slam_cmake_option_Eigen_INCLUDE_DIR
      $slam_cmake_option_Eigen_DIR
      $slam_cmake_option_glog_DIR
      $slam_cmake_option_Ceres_DIR
      $slam_cmake_option_nanoflann_DIR
      $slam_cmake_option_BOOST_ROOT
      $slam_cmake_option_Boost_DIR
      $slam_cmake_option_Boost_STATIC
      $slam_cmake_option_PCL_DIR
      $slam_cmake_option_g2o_DIR
      $slam_cmake_option_ParaView_DIR
      $slam_cmake_option_Qt5_DIR
      $slam_cmake_option_ZLIB_LIB
      $slam_cmake_option_ZLIB_INC
      $slam_cmake_option_PNG_LIB
      $slam_cmake_option_PNG_PNG_INC
      $slam_cmake_option_PYTHON"
    - cmake $CI_PROJECT_DIR
      $cmake_option_GENERATOR
      $cmake_option_build_type
      $cmake_option_shared
      -DSLAM_PARAVIEW_PLUGIN=ON
      $slam_cmake_option_Eigen_INCLUDE_DIR
      $slam_cmake_option_Eigen_DIR
      $slam_cmake_option_glog_DIR
      $slam_cmake_option_Ceres_DIR
      $slam_cmake_option_nanoflann_DIR
      $slam_cmake_option_BOOST_ROOT
      $slam_cmake_option_Boost_DIR
      $slam_cmake_option_Boost_STATIC
      $slam_cmake_option_PCL_DIR
      $slam_cmake_option_g2o_DIR
      $slam_cmake_option_ParaView_DIR
      $slam_cmake_option_Qt5_DIR
      $slam_cmake_option_ZLIB_LIB
      $slam_cmake_option_ZLIB_INC
      $slam_cmake_option_PNG_LIB
      $slam_cmake_option_PNG_PNG_INC
      $slam_cmake_option_PYTHON
    - cmake --build $build_dir -j 4

# Build PV wrapping on Linux
linux_paraview_wrapping:
  tags: [linux, paraview]
  extends:
    - .paraview_wrapping

# Build PV wrapping on Windows
windows_paraview_wrapping:
  tags: [windows, paraview]
  extends:
    - .windows_runner_config
    - .paraview_wrapping

# ------------------------------------------------------------------------------
#   Build ROS wrapping (on docker)
# ------------------------------------------------------------------------------

# Build ROS wrapping on linux
linux_ros_wrapping_build:
  tags: [linux, ros]
  stage: ros_wrapping_build
  needs: []
  image: gitlab.kitware.com:4567/keu-computervision/slam:ros1_noetic
  cache:
    - key: "ros-build"
      paths:
        - catkin_ws/
      policy: push
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
  script:
    # Create a hidden catkin workspace folder beside sources
    # This is used to move all files from the current directory
    - cmake -E make_directory .catkin_ws/src/slam
    # Move sources to workspace
    - mv * .catkin_ws/src/slam
    # Convert to not hidden folder to be able to cache it for next jobs
    - mv .catkin_ws catkin_ws
    # Compile
    - cd catkin_ws
    - source /opt/ros/noetic/setup.bash
    - catkin_make
      $cmake_option_build_type
      -j 4

# ------------------------------------------------------------------------------
#   Perform ROS tests (on docker)
# ------------------------------------------------------------------------------

# Create a reference for any test from master branch
.ros_make_reference:
  stage: ros_test
  tags: [linux, ros]
  needs: [linux_ros_wrapping_build]
  image: gitlab.kitware.com:4567/keu-computervision/slam:ros1_noetic
  variables:
    GIT_STRATEGY: none
  cache:
    - key: "ros-build"
      paths:
        - catkin_ws/
      policy: pull
    - key: "log"
      paths:
        - log/
      policy: pull-push
  only:
    - master
  script:
    - echo "Creating reference log files for $test_name for next lib improvements"
    - cmake -E remove_directory "log/${test_name}/reference"
    - cmake -E make_directory "log/${test_name}/reference"
    - cd catkin_ws
    - source /opt/ros/noetic/setup.bash
    - source devel/setup.bash
    - roslaunch lidar_slam_test slam.launch
      test_data:="$data_folder/${test_name}/${test_name}.bag"
      outdoor:=$outdoor
      vlp16:=$vlp16
      wait_init:=$wait_init
      res_path:="${CI_PROJECT_DIR}/log/${test_name}/reference"
      2>&1
      | grep "comparison ignored"

# HACK
hack:
  stage: ros_wrapping_build
  needs: []
  tags: [brave]
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  script:
    - sudo cp /var/lib/docker/volumes/runner-rtopvnvw-project-4640-concurrent-0-cache-3c3f060a0374fc8bc39395164f415a70/_data/keu-computervision/slam/log-protected/cache.zip /var/lib/docker/volumes/runner-rtopvnvw-project-4640-concurrent-0-cache-3c3f060a0374fc8bc39395164f415a70/_data/keu-computervision/slam/log-non_protected/cache.zip

# Perform test
.ros_test:
  stage: ros_test
  tags: [linux, ros]
  needs: [linux_ros_wrapping_build]
  image: gitlab.kitware.com:4567/keu-computervision/slam:ros1_noetic
  variables:
    GIT_STRATEGY: none
  cache:
    - key: "ros-build"
      paths:
        - catkin_ws/
      policy: pull
    - key: "log"
      paths:
        - log/
      policy: pull
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  script:
    - echo $test_name
    - cmake -E remove_directory "log/${test_name}/result"
    - cmake -E make_directory "log/${test_name}/result"
    - cd catkin_ws
    - source /opt/ros/noetic/setup.bash
    - source devel/setup.bash
    - roslaunch lidar_slam_test slam.launch
      test_data:="${data_folder}/${test_name}/${test_name}.bag"
      outdoor:=$outdoor
      vlp16:=$vlp16
      wait_init:=$wait_init
      ref_path:="${CI_PROJECT_DIR}/log/${test_name}/reference"
      res_path:="${CI_PROJECT_DIR}/log/${test_name}/result"
      2>&1
      | grep "Test successfully passed"

# Create a reference for test1 from master branch
ros_make_reference1:
  extends: .ros_make_reference
  variables:
    test_name: "test1"
    outdoor: "true"
    vlp16: "false"
    wait_init: "2" # To have time to init the process

# Create a reference for test2 from master branch
ros_make_reference2:
  extends: .ros_make_reference
  variables:
    test_name: "test2"
    outdoor: "false"
    vlp16: "true"
    wait_init: "4" # To have time to init the process

# Perform test 1
ros_test1:
  extends: .ros_test
  variables:
    test_name: "test1"
    outdoor: "true"
    vlp16: "false"
    wait_init: "2" # To have time to load the reference files

# Perform test 2
ros_test2:
  extends: .ros_test
  variables:
    test_name: "test2"
    outdoor: "false"
    vlp16: "true"
    wait_init: "4" # To have time to load the reference files