stages:
  - slam_lib
  - ros_wrapping
  - paraview_wrapping

# Default parameters for all jobs
default:
  before_script:
    - echo "Using additional cmake arguments that are defined by the runner $CMAKE_RUNNER_ARGS"

# ------------------------------------------------------------------------------
#   Build core LidarSlam lib
# ------------------------------------------------------------------------------

.slam_lib:
  stage: slam_lib
  needs: []
  variables:
    build_dir: $CI_PROJECT_DIR/../${CI_PROJECT_NAME}_build/build_slam_lib
  script:
    - cmake -E remove_directory $build_dir
    - cmake -E make_directory $build_dir
    - cd $build_dir
    - cmake
      -DCMAKE_BUILD_TYPE=Release
      -DBUILD_SHARED_LIBS=ON
      $CMAKE_RUNNER_ARGS $CI_PROJECT_DIR
    - cmake --build $build_dir -j 4

# Build core LidarSlam lib on Linux
linux_slam_lib:
  tags: [linux]
  extends: .slam_lib

# Build core LidarSlam lib on Windows
# TODO

# ------------------------------------------------------------------------------
#   Build ROS wrapping
# ------------------------------------------------------------------------------

.ros_wrapping:
  stage: ros_wrapping
  needs: []
  variables:
    build_dir: $CI_PROJECT_DIR/../${CI_PROJECT_NAME}_build/build_ros_wrapping
  script:
    - cmake -E remove_directory $build_dir
    - cmake -E make_directory $build_dir/src
    - cmake -E create_symlink $CI_PROJECT_DIR $build_dir/src/slam
    - cd $build_dir
    - catkin_make
      -DCMAKE_BUILD_TYPE=Release
      -j 4
      $CMAKE_RUNNER_ARGS

# Build ROS wrapping on Linux
linux_ros_wrapping:
  tags: [linux, ros]
  extends: .ros_wrapping

# ------------------------------------------------------------------------------
#   Build PV wrapping
# ------------------------------------------------------------------------------

.paraview_wrapping:
  stage: paraview_wrapping
  needs: []
  variables:
    build_dir: $CI_PROJECT_DIR/../${CI_PROJECT_NAME}_build/build_paraview_wrapping
  script:
    - cmake -E remove_directory $build_dir
    - cmake -E make_directory $build_dir
    - cd $build_dir
    - cmake
      -DCMAKE_BUILD_TYPE=Release
      -DBUILD_SHARED_LIBS=OFF
      -DSLAM_PARAVIEW_PLUGIN=ON
      $CMAKE_RUNNER_ARGS $CI_PROJECT_DIR
    - cmake --build $build_dir -j 4

# Build PV wrapping on Linux
linux_paraview_wrapping:
  tags: [linux, paraview]
  extends: .paraview_wrapping

# Build PV wrapping on Windows
# TODO
